### ISSUE TITLE
PHP 5.5 or PHP 5.6

### ISSUE THREAD

**Issue by joseska** [unreal4u/telegram-api#10]
It´s posible a versión with php 5.6???

Thanks....

**Comment by unreal4u** [comment]
Hi:
I will release v2.0.0 soon (including all API updates from may on) and I can then look into this.
On za, jun. 18, 2016 at 2:26 PM, joseska <notifications@github.com> wrote:
It´s posible a versión with php 5.6???

Thanks....

**Comment by joseska** [comment]
Thanks

**Comment by unreal4u** [comment]
With PHP 5.5 entering security updates only, this won't happen anymore. This package is and will remain PHP7+ only.

I'm closing this one now.
