### ISSUE TITLE
is there a way to delete a message in group chat?

### ISSUE THREAD

**Issue by jkyngan** [unreal4u/telegram-api#106]
i noticed there is DeleteMessageAsync method in the telegram official api.
is there a way to call it in the php bot?

**Comment by unreal4u** [comment]
I'm not able to find it here: https://core.telegram.org/bots/api

However, to delete messages, you can do so by calling up DeleteMessage: https://github.com/unreal4u/telegram-api/blob/master/src/Telegram/Methods/DeleteMessage.php

It requires only a chat_id and a message_id and you can call it however you want, async or sync.

Greetings.

**Comment by unreal4u** [comment]
Because there hasn't been any activity on this ticket, I'll close it. Feel free to reopen it if you need it 👍
