### ISSUE TITLE
How can I get the result from GetChatAdministrators?

### ISSUE THREAD

**Issue by nikelanjelo** [unreal4u/telegram-api#124]
`$GetChatAdministrators = new unreal4u\TelegramAPI\Telegram\Methods\GetChatAdministrators();`
`$GetChatAdministrators->chat_id = $update->message->chat->id;`
`$tgLog->performApiRequest($GetChatAdministrators);`

How can I get **results** after that?

**Comment by unreal4u** [comment]
Hi! 

I would suggest to take a look at the examples directory where you can find a very similar example using getChatMember:

```
$getChatMemberPromise = $tgLog->performApiRequest($getChatMember);
$getChatMemberPromise->then(
    function ($response) {
        echo '<pre>';
        var_dump($response);
        echo '</pre>';
    },
    function (\Exception $exception) {
        // Onoes, an exception occurred...
        echo 'Exception ' . get_class($exception) . ' caught, message: ' . $exception->getMessage().PHP_EOL;
    }
);
```

https://github.com/unreal4u/telegram-api/blob/master/examples/get-chat-member.php

Greetings.
