### ISSUE TITLE
need to do some actions one by one

### ISSUE THREAD

**Issue by kur1977** [unreal4u/telegram-api#133]
Hi.
I need delete message immediately, than do some staff and then send a message.
Doing this staff takes a long time.
I wrote my code like this:
`$tgLog->performApiRequest($deleteMessage);

/// doing some staff there - it takes long time

$tgLog->performApiRequest($sendMessage);

$loop->run();`
But when I send message to bot - I see that nothing happens long time than I see the message delete and appear a new message in the one moment.

But I need first delete the message and than doing stuff and then send a message.

**Comment by unreal4u** [comment]
Hi

If you need to delete a message immediately, you need to make it a blocking request: 
https://github.com/unreal4u/telegram-api/blob/master/examples/01.blocking-get-me.php

**After** that blocking request, you can resume the normal flow.

**Comment by kur1977** [comment]
@unreal4u 
Thanks! It's worked.
The library is very cool.
