### ISSUE TITLE
https://github.com/unreal4u/telegram-api/issues/131#issue-775669069

### ISSUE THREAD

**Issue by Modusto** [unreal4u/telegram-api#134]
## Which version are you using?

Hint: find out with composer which version you are currently running:  
`composer.phar show | grep telegram-api`

Output:
```
# Paste output here
```

**Comment by Modusto** [comment]
https://github.com/unreal4u/telegram-api/issues/131#issue-775669069

**Comment by Modusto** [comment]
Wassup can I run some bitcoins along the way here some where how about some ethereum s or some litecoin a man tell me some thing somebody i want to do this shit like right now and make get and have some fucking k on ey iny no icj see

**Comment by unreal4u** [comment]
Spam?
