### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by unreal4u** [unreal4u/telegram-api#16]
A preview of the general idea is committed to the branch https://github.com/unreal4u/telegram-api/tree/errorHandler , but this needs some more work as I'm not convinced that that implementation is the best one.

**Comment by Yoshi2889** [comment]
Starting from #55, an error can be identified by a rejected Promise. The RequestHandler rejects it with a TelegramResponse, which is populated if valid data was received.

**Comment by unreal4u** [comment]
Closing this one as it works, I will however check for some pitfalls tomorrow before launching a new version.
