### ISSUE TITLE
how use it in laravel 

### ISSUE THREAD

**Issue by aliayoubi** [unreal4u/telegram-api#19]
how use thid api in laravel

**Comment by unreal4u** [comment]
Hello: I've never have used Laravel before, but this package is framework agnostic, so you may use it as you want.

Some bot examples: https://github.com/unreal4u/telegram-bots/tree/robustBotImplementations
Monolog integration: https://github.com/unreal4u/monolog-telegram
Examples directory: https://github.com/unreal4u/telegram-api/tree/master/examples

Greetings.

**Comment by unreal4u** [comment]
No more comments on this, so closing it
