### ISSUE TITLE
Error on the "Getting updates via Webhook" wiki page

### ISSUE THREAD

**Issue by skobkin** [unreal4u/telegram-api#20]
```php
use \unreal4u\TelegramAPI\Telegram\Types\Update;

$update = new Update($_POST);
```

It does not work because Telegram webhook servers are sending data using JSON-serialized POST body (not plain parameters).

> There are two mutually exclusive ways of receiving updates for your bot — the getUpdates method on one hand and Webhooks on the other. Incoming updates are stored on the server until the bot receives them either way, but they will not be kept longer than 24 hours.
> Regardless of which option you choose, you will receive **JSON-serialized Update objects as a result**.

So one of the simpliest examples must look like that:

```php
use \unreal4u\TelegramAPI\Telegram\Types\Update;

$data = json_decode(file_get_contents('php://input'), true);

$update = new Update($data);
```

Correct me if I'm wrong, please.

**Comment by unreal4u** [comment]
You are absolutely right, thanks for spotting the error! Will fix the wiki a bit later on, I'm on my phone now. 

Greetings.

**Comment by skobkin** [comment]
Ok, looks like I can correct it myself. Just done it. Have a nice holidays :)

**Comment by unreal4u** [comment]
Great, thanks!
