### ISSUE TITLE
Implement payment options

### ISSUE THREAD

**Issue by unreal4u** [unreal4u/telegram-api#24]
Payment options must be implemented

**Comment by kettari** [comment]
Any deadlines? Need help?

**Comment by unreal4u** [comment]
Hi! This is already implemented in https://github.com/unreal4u/telegram-api/releases/tag/v2.4.0 , however there are no unit tests yet. I will eventually get to it, but that would be nice :)

Thanks!

**Comment by kettari** [comment]
Writing unit tests is not my strong side 😄 If I will be able to create something useful -- I'll create pull request.

**Comment by unreal4u** [comment]
That's fine as well, and if you encounter any problems while implementing your bot with this API client, don't hesitate to create either an issue or a pull request :)
