### ISSUE TITLE
Update to Bot API 3.0

### ISSUE THREAD

**Issue by kettari** [unreal4u/telegram-api#29]
Hi,

Do you plan to update your API to reflect recent [Telegram Bot API changes](https://core.telegram.org/bots/api#may-18-2017)?

**Comment by kettari** [comment]
May be it's better to keep some issue pinned... Just found closed one: #24

**Comment by unreal4u** [comment]
Hi! It is already done, I made a project with all necessary issues: https://github.com/unreal4u/telegram-api/projects/2#card-2981242
However I must agree with you that the interface could get some attention, it is hard to find what is exactly done and what not.

Another way to check which version is the latest, is to check the following description: https://github.com/unreal4u/telegram-api#telegram-api
This will always tell you which version of the Telegram Bot API is currently supported.

In this case, 2 hours after Telegram announced a new version of their Bot API, it was already fully implemented :)

**Comment by kettari** [comment]
Thanks! 👍
