### ISSUE TITLE
PreCheckoutQuery doesnt morph `from` json string to object

### ISSUE THREAD

**Issue by ircop** [unreal4u/telegram-api#33]
It's me again with another issue, sorry ^^

print_r of PreCheckoutQuery received from Telegram API:

```
[19.06.2017 23:46:43] TgPay: PreCheckout query: unreal4u\TelegramAPI\Telegram\Types\PreCheckoutQuery Object
(
    [id] => 175373356413545972
    [from] => {"id":111111,"first_name":"222222","username":"123","language_code":"ru"}
    [currency] => USD
    [total_amount] => 100
    [invoice_payload] => 2222
    [shipping_option_id] =>
    [order_info] =>
    [logger:protected] => unreal4u\TelegramAPI\InternalFunctionality\DummyLogger Object
        (
        )

)
```

So, when trying to use `from` object, we are getting `Trying to get property of non-object` error

**Comment by unreal4u** [comment]
Oh that's strange, I thought I had fixed that with https://github.com/unreal4u/telegram-api/commit/aafcb0285827caa238fe9bdb2cc122d583785790#diff-f266a2d668215992af6d6d9531cdfbb7 . 

Will look into it! Thanks for reporting 👍

**Comment by ircop** [comment]
Oh, sorry, i've not updated to the very latest version (updated 2 hours before my report)

Now it seems good
