### ISSUE TITLE
Fatal error on webhookinfo.php example

### ISSUE THREAD

**Issue by Ardaking** [unreal4u/telegram-api#35]
Hi all,
into webhookinfo.php example there is a problem with capital letters on line 7 and 12.
the G of getWebhookInfo is Capital letter.

Thanks

**Comment by unreal4u** [comment]
As strange as it is... I use a linux box myself to test every example, and this passed, not so long ago. 

I will definitively have to find out why my specific linux box allows this situation, where it clearly shouldn't. 

Thanks for reporting it!
