### ISSUE TITLE
how to use this file to get file id

### ISSUE THREAD

**Issue by mkiany4** [unreal4u/telegram-api#41]
hi.. i am android programmer. i want to get file id from telegram with your php file. How can I do this?

**Comment by unreal4u** [comment]
Hello: 

a file_id will always come within an update, webhook or any other message object, so for example, should you receive a document within an update, you would do: 

```
$fileId = $update->message->document->file_id;
```

Greetings.

**Comment by unreal4u** [comment]
I'm closing this because no further action is needed. Should you have any more (related) questions, feel free to reopen or create new issue :)

Thanks!
