### ISSUE TITLE
problem with use

### ISSUE THREAD

**Issue by rahnamayeavval** [unreal4u/telegram-api#42]
![cdsdsdsdsapture](https://user-images.githubusercontent.com/30045350/28016559-271b4036-658a-11e7-8dca-3a7ce224d3cf.PNG)
hi
extract in root host
how solve this problem

**Comment by unreal4u** [comment]
Hi! Have you tried out installing this package via Composer? 

I did write a _basic_ introduction about composer here: https://github.com/unreal4u/telegram-api/wiki/Composer-basics

That should help you the right way :)

Greetings.

**Comment by unreal4u** [comment]
Since I've received no answer back so far, I'll close this issue. Should you have any question, don't hesitate to re-open it.

Greetings.
