### ISSUE TITLE
[question] error treatment

### ISSUE THREAD

**Issue by umbri** [unreal4u/telegram-api#64]
if we here get an error from PromiseInterface, no one will report.

https://github.com/unreal4u/telegram-api/blob/master/src/TgLog.php#L89

**Comment by kelunik** [comment]
@umbri The returned promise just fails.

**Comment by umbri** [comment]
@kelunik It is silently ignored, i think it must be something like this https://github.com/umbri/telegram-api/blob/master/src/TgLog.php#L93

If something goes wrong (ex: you set invalid A_GROUP_CHAT_ID), request fail but you get nothing, even with Logger

**Comment by unreal4u** [comment]
You are absolutely right, the logger should at least log the error, good catch.

Exceptions however can be captured, you just have to define a second closure, as seen in the following example: https://github.com/unreal4u/telegram-api/blob/master/examples/get-chat-member.php

However, I think the most basic examples should include some way of capturing exceptions. Will definitely include an example with this.

Commit c568622e6 however broke this, so I fixed it in 9e0f6818f6e9 .

Hope this resolves your doubts 👍
