### ISSUE TITLE
bot stops after 60 seconds.

### ISSUE THREAD

**Issue by peyman-fx** [unreal4u/telegram-api#67]
Hi,
thank you for this sdk,
I have a messenger bot, and I must send a message at a time to more than 1000 records. It takes about 2 minutes.
But exactly after 60 seconds I receive the following message in the DirectAdmin log And posting will be unfinished.

 `Abort request processing by PID:440707, kill: 1, begin time: 61, sent time: 61, req processed: 1`

And again, when the request from telegram is sent, it begins to send duplicate messages.
I will respond to the request by using the following code, and then I doing the pending_update_count to zero and the message does not repeat.

```
set_time_limit(600);
ignore_user_abort(true);
$out =  json_encode([
	'method'=>'sendMessage',
	'chat_id'=>$update->message->chat->id,
	'text'=> "Starting process..."
]);   
header('Connection: close');
header("Content-type:application/json");
ob_start();          
echo $out;   
header("Content-Length: ".ob_get_length(),TRUE);  
ob_end_flush();
ob_flush();
flush(); 
	
if (function_exists('fastcgi_finish_request')) {
	fastcgi_finish_request();
}  
```
But after 60 seconds, I still get the previous error message and Sends will be stop.
I do not know why it's still stopping. Do you know the solution?
Thank you
Peyman

**Comment by unreal4u** [comment]
Hi! 

A few things I see:
1. Is it possible that you are using LightSpeed? I'm not familiar with that package, but it seems the error you are seeing is being generated from that software.
One posted solution for this, is going to server->General tab, under General Setting table, there is an "External application abort", set it to "no abort".
( https://www.litespeedtech.com/support/forum/threads/lots-of-abort-requests.7444/#post-74526 )

2. You can set an offset to getUpdates. This offset will allow you to automatically lower the pending_update_count. You can do this by giving a number 1 greater than the last update id you've received.

3. You are not sending any messages out in the above code, you are just printing a json-encoded string. In fact, the above request, as it is, shouldn't take more than 0.1 second to complete.

Greetings.

**Comment by peyman-fx** [comment]
Thank you for your respond so quickly 👍
Yes, l use LiteSpeed and you said right. Problem is "External application abort" .
Finally, the problem was fixed by the following value in the .htaccess
```
RewriteEngine On
RewriteRule .* - [E=noabort:1]
```
Thanks for your help
Greetings.

**Comment by unreal4u** [comment]
Great, success with your bot!
