### ISSUE TITLE
Async Guzzle

### ISSUE THREAD

**Issue by Doncode** [unreal4u/telegram-api#7]
What do you think about async Guzzle for send multi message?

**Comment by unreal4u** [comment]
I'm afraid I don't understand your question completely... I think you're asking whether I support the async mode of Guzzle to send out multi messages... In that case, not yet, but I'll be working on it very soon, I think v2.1.0 once v2.0.0 gets out on the open.

**Comment by Doncode** [comment]
Thanks!
