### ISSUE TITLE
Using the classes of the API in my class

### ISSUE THREAD

**Issue by sallsabil** [unreal4u/telegram-api#73]
Hello
Thanks for your good job.
I have a question maybe not related to the API directly.

How can I use these classes:
`use unreal4u\TelegramAPI\Telegram\Types\KeyboardButton;`
`use unreal4u\TelegramAPI\Telegram\Types\ReplyKeyboardMarkup;`

In my function KeywordCommand:
`class Commands {`
`.......`
`	public function KeywordCommand() {`
`	$this->sendMessage->chat_id = $this->chatId;`
`	$this->sendMessage->text = "text";`
`	$this->sendMessage->parse_mode = 'HTML';`
`	$sendMessage->reply_markup = new ReplyKeyboardMarkup();`
`	$keyboardButton = new KeyboardButton();`
`	$keyboardButton->text = 'text';`
`	$sendMessage->reply_markup->keyboard[0][] = $keyboardButton;`
`	$sendMessage->reply_markup->resize_keyboard = true;`
`	$this->tgLog->performApiRequest($this->sendMessage);`
`	$this->loop->run();`
`	}`
`	}`

?

**Comment by unreal4u** [comment]
Hi! 

There is an [example over here](https://github.com/unreal4u/telegram-api/blob/b305b66c547cf3109b9e98ea940c532c9587fc09/examples/send-message-with-keyboard-options.php) which will produce [the following output](https://github.com/unreal4u/telegram-api/blob/master/examples/send-message-with-keyboard-options.png). You can take that as an entry point to further customize it to your needs :) 

So in your example, I would do something like: 

```php
public function KeywordCommand() {
    $this->sendMessage->chat_id = $this->chatId;
    $this->sendMessage->text = "text";
    $this->sendMessage->parse_mode = 'HTML';
    $sendMessage->reply_markup = new ReplyKeyboardMarkup();

    $keyboardButton = new KeyboardButton();
    $keyboardButton->text = 'text';
    $sendMessage->reply_markup->keyboard[0][] = $keyboardButton;

    $sendMessage->reply_markup->resize_keyboard = true;

    $this->tgLog->performApiRequest($this->sendMessage);
    $promise = $tgLog->performApiRequest($sendMessage);

    $promise->then(
        function ($response) {
            echo '<pre>';
            var_dump($response);
            echo '</pre>';
        },
        function (\Exception $exception) {
            // Onoes, an exception occurred...
            echo 'Exception ' . get_class($exception) . ' caught, message: ' . $exception->getMessage();
        }
    );
    $this->loop->run();
}
```

Greetings.

**Comment by sallsabil** [comment]
My problem is the function is in the class 'Commands'.
So my question is How to get 'ReplyKeyboardMarkup();' or 'KeyboardButton();' which are in the 'Commands' class ?

Thank you

**Comment by unreal4u** [comment]
Oh that warning comes up when you don't declare the object first... 

I'll need to see some more code and warnings, because it could be a variety of stuff that goes wrong: are you using composer? Are you importing the libraries? Are you initializing your class? etc... 

Greetings.

**Comment by sallsabil** [comment]
1. Yes
2. Yes
3. I'm not sure.

My codes:
```
<?php
require "/root/vendor/autoload.php";
use \React\EventLoop\Factory;
use \unreal4u\TelegramAPI\HttpClientRequestHandler;
use \unreal4u\TelegramAPI\TgLog;
use \unreal4u\TelegramAPI\Telegram\Methods\SendMessage;
use \unreal4u\TelegramAPI\Telegram\Methods\DeleteMessage;
use unreal4u\TelegramAPI\Telegram\Types\KeyboardButton;
use unreal4u\TelegramAPI\Telegram\Types\ReplyKeyboardMarkup;
require __DIR__ . '/settings.php';

$loop = Factory::create();
$handler = new HttpClientRequestHandler($loop);
$tgLog = new TgLog(BOT_TOKEN, $handler);

$updates = json_decode(file_get_contents('php://input'), true);
$sendMessage = new SendMessage();
$deleteMessage = new DeleteMessage();


class Commands {
// some other codes and functions
public function KeywordCommand() {
$this->sendMessage->chat_id = $this->chatId;
$this->sendMessage->text = "text";
$this->sendMessage->parse_mode = 'HTML';
$sendMessage->reply_markup = new ReplyKeyboardMarkup();
$keyboardButton = new KeyboardButton();
$keyboardButton->text = 'text';
$sendMessage->reply_markup->keyboard[0][] = $keyboardButton;
$sendMessage->reply_markup->resize_keyboard = true;
$this->tgLog->performApiRequest($this->sendMessage);
$this->loop->run();
}
}
```

Everything works fine. Just I don't know how to get for example KeyboardButton(); in a function which is in a class.

**Comment by unreal4u** [comment]
If you have a use statement, it will import the class automatically for you (technically it won't do that, but for simplicity, let's assume that), and it doesn't matter where in the same file you actually call the class up.

What do you do to run this code and in which file:line do you get the warning? What does your constructor look like and where do you initialize stuff like `$this->sendMessage` and `$this->loop` ?

By initializing your class, I mean that you'll have to have something around these lines in your code:

```php
$commands = new Commands();
$commands->setLoop($loop);
$commands->setSendMessageObject($sendMessage);

$commands->KeywordCommand();
```

Greetings.

**Comment by sallsabil** [comment]
Sorry I had sent the error wrong.
The error is this:
PHP Fatal error:  Uncaught Error: Class 'ReplyKeyboardMarkup' not found in 

For this line:
$sendMessage->reply_markup = new ReplyKeyboardMarkup();

**Comment by sallsabil** [comment]
Solved
I used this:
\unreal4u\TelegramAPI\Telegram\Types\ReplyKeyboardMarkup();

Also I forgot to put $this-> at the begining.

Thank you @unreal4u

**Comment by unreal4u** [comment]
You're welcome! Closing this one
