### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Elmit2015** [unreal4u/telegram-api#77]
The installation hint is not complete ;-(

I installed and used exactly the example.php as shown, with my BOT_TOKEN ("12345678:xxxxxxx") in quote marks. 

I get the following response to php example.php 
```
PHP Warning:  include(/home/ronald/example.com/MyTelegram/basics.php): failed to open stream: No such file or directory in /home/ronald/example.com/MyTelegram/example.php on line 5
PHP Warning:  include(): Failed opening '/home/ronald/example.com/MyTelegram/basics.php' for inclusion (include_path='.:/usr/share/php') in /home/ronald/example.com/MyTelegram/example.php on line 5
PHP Fatal error:  Uncaught Error: Class 'React\EventLoop\Factory' not found in /home/ronald/example.com/MyTelegram/example.php:12
Stack trace:
#0 {main}
  thrown in /home/ronald/example.com/MyTelegram/example.php on line 12

```

**Comment by unreal4u** [comment]
Hi! 

May I ask you which directions you followed in order to correct it? 

Also: all the example files will try to include some common values defined in basics.php. What you define here is up to you 👍 

Greetings,
Camilo Sperberg

**Comment by Elmit2015** [comment]
I followed: https://github.com/unreal4u/telegram-api/wiki/Composer-basics

I put that example.php into the basis directory.

> MyTelegram$ tree -L 2
.
├── composer.json
├── composer.lock
├── composer.phar
├── example.php
├── example.php~
└── vendor
    ├── amphp
    ├── autoload.php
    ├── clue
    ├── composer
    ├── daverandom
    ├── evenement
    ├── guzzlehttp
    ├── kelunik
    ├── psr
    ├── react
    ├── unreal4u
    └── yoshi2889

**Comment by unreal4u** [comment]
I have updated the wiki, can you try again please? 👍 

Greetings,
Camilo Sperberg

**Comment by Elmit2015** [comment]
Thanks! That works now.

**Comment by unreal4u** [comment]
Great! Closing this issue now :) Should you have any more questions, feel free to create new ones!

Greetings,
Camilo Sperberg
