### ISSUE TITLE
PHP Fatal error:  Class 'React\EventLoop\Factory' not found

### ISSUE THREAD

**Issue by AlexNoxious** [unreal4u/telegram-api#78]
Hello, my name is Diego.
I'm using the "telegram-api" library to send messages ("send-message.php"),
I have placed and replaced all the values and the routes but when I run it returns the error:

` PHP Fatal error: Class 'React\EventLoop\Factory' not found  `

I have a Shared Hosting, there I am doing the tests. How do I solve the problem?

Thanks

**Comment by unreal4u** [comment]
Hi Diego! 

That error means basically that either you are not loading vendor/autoload.php in or you don't have the dependencies downloaded. 

Please make sure you have executed composer either locally (and then uploaded everything) or, if you can execute composer on your host, do it there. 

In the wiki section you can find more information about how to do this. Good luck!

**Comment by AlexNoxious** [comment]
Thank you.
I have consulted with my Hosting, and they do not give me access to SSH.
Can I use "telegram-api" without the autoloader?
I have some other option?

Regards

**Comment by unreal4u** [comment]
Yes, download dependencies locally and upload them via sftp. 

Greetings.

**Comment by AlexNoxious** [comment]
Thank you.
I have managed to upload the dependencies locally, I have solved the problem.
Now I have the following error:

  PHP Fatal error: Class 'src \ HttpClientRequestHandler' not found in /home/user/public_html/bot/send1.php on line 10

I have reviewed and the route is correct, the file is .php is there.
I have also reviewed the permits and they are in 644.

I still can not find the problem.
My code:

`
<?php
require 'vendor/autoload.php';


use src\HttpClientRequestHandler;
use src\Telegram\Methods\SendMessage;
use src\TgLog;

$loop = \React\EventLoop\Factory::create();
$handler = new HttpClientRequestHandler($loop);
$tgLog = new TgLog('MY_TOKEN', $handler);

$sendMessage = new SendMessage();
$sendMessage->chat_id = MY_CHAT_ID;
$sendMessage->text = 'Hello world!';

$tgLog->performApiRequest($sendMessage);
$loop->run();

?>


`

**Comment by unreal4u** [comment]
Great! 

The namespace is incorrect, I'm writing on the phone right now but take a look at the example directory, the correct namespaces are used there. 

Greetings.

**Comment by AlexNoxious** [comment]
I have reviewed and updated my code, but the problem persists.

<?php

declare(strict_types = 1);

require 'vendor/autoload.php';
include 'basics.php';


use React\EventLoop\Factory;
use src\HttpClientRequestHandler;
use src\Telegram\Methods\SendMessage;
use src\TgLog;

$token= "MY_TOKEN";

$loop = Factory::create();
$handler = new HttpClientRequestHandler($loop);
$tgLog = new TgLog($token, $handler);

$sendMessage = new SendMessage();
$sendMessage->chat_id = CHAT_ID;
$sendMessage->text = 'Hello world to the user... from a specialized getMessage file';

$promise = $tgLog->performApiRequest($sendMessage);

$promise->then(
    function ($response) {
        echo '<pre>';
        var_dump($response);
        echo '</pre>';
    },
    function (\Exception $exception) {
        // Onoes, an exception occurred...
        echo 'Exception ' . get_class($exception) . ' caught, message: ' . $exception->getMessage();
    }
);


$sendMessage = new SendMessage();
$sendMessage->chat_id = CHAT_ID;
$sendMessage->text = 'And this is an hello the the group... also from a getMessage file';

$promise = $tgLog->performApiRequest($sendMessage);

$promise->then(
    function ($response) {
        echo '<pre>';
        var_dump($response);
        echo '</pre>';
    },
    function (\Exception $exception) {
        // Onoes, an exception occurred...
        echo 'Exception ' . get_class($exception) . ' caught, message: ' . $exception->getMessage();
    }
);

$loop->run();


?>


I have installed the dependencies:
`react/event-loop`
`react/http-client`

The error that returns:

Fatal error: Class 'src\HttpClientRequestHandler' not found...

In "HttpClientRequestHandler.php" i have:
"
...
declare(strict_types=1);

namespace \src;

use React\EventLoop\LoopInterface;
use React\HttpClient\Client;
use React\HttpClient\Request;
use React\HttpClient\Response;
use React\Promise\Deferred;
use React\Promise\PromiseInterface;
use React\Socket\Connector;
use src\Exceptions\ClientException;
use src\InternalFunctionality\TelegramResponse;
...
"

**Comment by unreal4u** [comment]
If you have modified this package, try first of all revert all changes: a package is a package and should not be modified to make it work.

Your composer.json should look like this: 

```json
{
  "require": {
    "unreal4u/telegram-api": "~3.3"
}
```

Then, you should be able to make a script with the following contents:

```php
<?php 

declare(strict_types=1);

require 'vendor/autoload.php';

use React\EventLoop\Factory;
use unreal4u\TelegramAPI\HttpClientRequestHandler;
use unreal4u\TelegramAPI\TgLog;
use unreal4u\TelegramAPI\Telegram\Methods\SendMessage;

$token= "MY_TOKEN";

$loop = Factory::create();
$handler = new HttpClientRequestHandler($loop);
$tgLog = new TgLog($token, $handler);

$sendMessage = new SendMessage();
...
```

Greetings.

**Comment by AlexNoxious** [comment]
Hi. I have corrected the previous problem. I have reinstalled the composer along with the dependencies and now it's all OK.
But now the error log shows me this:

```
[09-Feb-2018 16:58:59 America/Argentina/Buenos_Aires] PHP Warning:  Unsupported declare 'strict_types' in /home/user999a/public_html/bot/vendor/unreal4u/telegram-api/examples/send-message.php on line 3
[09-Feb-2018 16:58:59 America/Argentina/Buenos_Aires] PHP Warning:  require_once(/home/user999a/public_html/bot/vendor/unreal4u/telegram-api/examples/vendor/autoload.php): failed to open stream: No such file or directory in /home/user999a/public_html/bot/vendor/unreal4u/telegram-api/examples/send-message.php on line 6
[09-Feb-2018 16:58:59 America/Argentina/Buenos_Aires] PHP Fatal error:  require_once(): Failed opening required '/home/user999a/public_html/bot/vendor/unreal4u/telegram-api/examples/vendor/autoload.php' (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/user999a/public_html/bot/vendor/unreal4u/telegram-api/examples/send-message.php on line 6
```

My new code is the following:

```
<?php

declare(strict_types = 1);


include __DIR__.'/basics.php';


use React\EventLoop\Factory;
use unreal4u\TelegramAPI\HttpClientRequestHandler;
use unreal4u\TelegramAPI\Telegram\Methods\SendMessage;
use unreal4u\TelegramAPI\TgLog;

$token= "MY_TOKEN";

$loop = Factory::create();
$tgLog = new TgLog($token, new HttpClientRequestHandler($loop));

$sendMessage = new SendMessage();
$sendMessage->chat_id = A_USER_CHAT_ID;
$sendMessage->text = 'Hello world to the user... from a specialized getMessage file';

$promise = $tgLog->performApiRequest($sendMessage);

$promise->then(
    function ($response) {
        echo '<pre>';
        var_dump($response);
        echo '</pre>';
    },
    function (\Exception $exception) {
        // Onoes, an exception occurred...
        echo 'Exception ' . get_class($exception) . ' caught, message: ' . $exception->getMessage();
    }
);


$sendMessage = new SendMessage();
$sendMessage->chat_id = GROUP_ID;
$sendMessage->text = 'And this is an hello the the group... also from a getMessage file';

$promise = $tgLog->performApiRequest($sendMessage);

$promise->then(
    function ($response) {
        echo '<pre>';
        var_dump($response);
        echo '</pre>';
    },
    function (\Exception $exception) {
        // Onoes, an exception occurred...
        echo 'Exception ' . get_class($exception) . ' caught, message: ' . $exception->getMessage();
    }
);

$loop->run();
```

and my "composer.json":

```
{
    "require": {
        "react/event-loop": "^0.4.3",
        "react/http-client": "^0.5.7",
        "unreal4u/telegram-api": "^3.3"
    }
}

```

Is any dependency missing? The routes are incorrect?



Thanks

**Comment by unreal4u** [comment]
@AlexNoxious You need at least php7.0 in order to execute this package.

**Comment by AlexNoxious** [comment]
Hello,
Problem solved!

Thank you

**Comment by unreal4u** [comment]
Nice to know, closing this one :)
