### ISSUE TITLE
Send emojis

### ISSUE THREAD

**Issue by AlexNoxious** [unreal4u/telegram-api#81]
Hello how are you,
I would like to know how to send emojis in a message.
This is possible?.

Example:

```
$sendMessage->parse_mode= 'HTML';
$sendMessage->text = 'U+1F601	 <b> text</b> '.$var. ' ,<b>text:</b>'.number_format($value , 3);
```

Thanks

**Comment by unreal4u** [comment]
Yes, it is possible, here is an example of how I send emoji's: https://github.com/unreal4u/telegram-bots/blob/master/src/Bots/uptimeMonitorBot.php#L194

Basically, you'll have to send Telegram the hexadecimal code of the emoji you are trying to send. Such codes can be found on sites like fileformat: http://www.fileformat.info/info/unicode/char/1f534/index.htm

There may be simpler ways, but the one above has worked fine for me.

Greetings.

**Comment by AlexNoxious** [comment]
Problem solved.
Thank you very much.

**Comment by unreal4u** [comment]
Great!

**Comment by ekankyesme** [comment]
Hello
