### ISSUE TITLE
Send URL with variables

### ISSUE THREAD

**Issue by AlexNoxious** [unreal4u/telegram-api#82]
Dear,

I have problems sending URL with variables, such as:

`$url= "https://google.com/{$var}";`

If I want to send a link via message to a telegram group, I get an error.

My code:

```
...
$sendMessage->parse_mode = 'HTML'; 
$sendMessage->disable_web_page_preview = true; 
$sendMessage->text ='<a href='.$url.'>inline URL</a>' ;  
...
```
The URL only supports pure string. But when I concatenate the string with a variable (as I mentioned above) it gives me the following error:

`Exception unreal4u\TelegramAPI\Exceptions\ClientException caught, message: Bad Request: can't parse entities: Unexpected end of name token at byte offset 8`

I have Composer installed correctly and it is updated. I have php 7.0.

I have an alternative to solve it?

**Comment by unreal4u** [comment]
@AlexNoxious Hi! Have you tried to send an url-encoded url instead? 

Check out the urlencode() function out on php.net for more information :)

**Comment by unreal4u** [comment]
Oh sorry, it was htmlentities(), not urlencode: 

https://github.com/unreal4u/telegram-bots/blob/master/src/Bots/uptimeMonitorBot.php#L194-L197

I knew I had done something with url's elsewhere xD

**Comment by AlexNoxious** [comment]
Hello,
It has not worked for me.
I solved it with this trick:

```
 $search = array('/object');
 $replace = array('/'.$object);  //variable
...
 $sendMessage->parse_mode = 'HTML'; 
 $sendMessage->disable_web_page_preview = true;
 $subject  = $imgS.' '. $img. '<b> Value1: </b><a href="https://example.com/account/tokenxxxxxxxxxx/object">'.$object.'</a><b> Value2:</b>'.number_format($OtherVar , 3).' '.$imgUD;
    
$sendMessage->text = str_replace($search,$replace,$subject); 
```

Solved!
Regards
