### ISSUE TITLE
I don't understand this error

### ISSUE THREAD

**Issue by sallsabil** [unreal4u/telegram-api#84]
Composer version @package_branch_alias_version@ (1.0.0-beta2) 2016-03-27 16:00:34
unreal4u/telegram-api         v3.3.3 

Output:
```
Bad Request: can't parse entities: Unsupported start tag "〰🌟" at byte offset 45
```

I don't understand the error.
They are just emojis: 〰🌟
What is the problem ?

**Comment by unreal4u** [comment]
@sallsabil Hi! Emoticons must be sent with their hexadecimal code. An example of this can be found here: https://github.com/unreal4u/telegram-bots/blob/master/src/Bots/uptimeMonitorBot.php

At line 195 and 249.

**Comment by unreal4u** [comment]
Hi! Did the above solve your problem?

**Comment by sallsabil** [comment]
I used converting to utf-8 but sometimes receive such an error!

**Comment by unreal4u** [comment]
Encoding the emoticon with their hexadecimal code should do the trick ;) 

I'll close this for now, but feel free to reopen should you have any more questions!
