### ISSUE TITLE
Send message options

### ISSUE THREAD

**Issue by gubi** [unreal4u/telegram-api#86]
## Which version are you using?

Output:
```
unreal4u/telegram-api       v3.3.3  A complete Telegram bot API implementation written in PHP, with support for inline bots!
```

## Description of problem
Is there a way to send a message with native options?
See https://core.telegram.org/bots/api#sendmessage

**Comment by unreal4u** [comment]
Yes, and in fact this api tries to resemble telegram's api as close as possible. 

The sendmessage method does in fact implement all options: https://github.com/unreal4u/telegram-api/blob/master/src/Telegram/Methods/SendMessage.php

You can take a look at the examples folder for more examples: )

Greetings.

**Comment by unreal4u** [comment]
Hi! 

Did my answer helped you? I'll close this due to inactivity, but feel free to reopen if you deem it necessary.

Greetings.
