### ISSUE TITLE
Cannot run the README example code

### ISSUE THREAD

**Issue by djnotes** [unreal4u/telegram-api#93]
## v3.4.1

Output:
```
PHP Fatal error:  Uncaught Error: Class 'React\EventLoop\Factory' not found in /home/johndoe/src/testTelegramApi/test.php:7

```

## Description of problem

I am just creating a  test project (using composer), in order to test the example code. But php fails to find the class React\EventLoop\Factory when I run `php -f test.php`.     

### test.php contents:   
```
<?php

use \unreal4u\TelegramAPI\HttpClientRequestHandler;
use \unreal4u\TelegramAPI\TgLog;
use \unreal4u\TelegramAPI\Telegram\Methods\SendMessage;

$loop = \React\EventLoop\Factory::create();
$handler = new HttpClientRequestHandler($loop);
$tgLog = new TgLog('SOMETOKEN', $handler);

$sendMessage = new SendMessage();
$sendMessage->chat_id = 'SOMEID';
$sendMessage->text = 'Hello world!';

$tgLog->performApiRequest($sendMessage);
$loop->run();
```

**Comment by unreal4u** [comment]
Hi! I see you are missing the: 

`include vendor/autoload.php`

from Composer, could you try adding that?

**Comment by unreal4u** [comment]
That being said, there is no mention of that anywhere in the documentation, I will fix that, please don't close this issue otherwise I'll forget it :)

Greetings.

**Comment by djnotes** [comment]
You are right.  Adding the following include statement to the above code solved the issue:   
```
include ('vendor/autoload.php');
```

**Comment by unreal4u** [comment]
@djnotes Great! Please don't close this issue otherwise I'll forget to add the comment in the README (you can also do it if you feel like it)

**Comment by djnotes** [comment]
@unreal4u  I added a side note to README.md. Feel free to merge if it is correct.   
Thanks

**Comment by unreal4u** [comment]
Done! Thank you!

Also maybe useful information: you must create a pull request once you've implemented the changes, otherwise I won't see anything to be merged :) If you hadn't told me here, I would have never even seen it.

You can do so by creating some changes and on the following page, a green button should appear saying "Create Pull Request": https://services.github.com/on-demand/github-cli/open-pull-request-github

Greetings!

**Comment by djnotes** [comment]
Sorry I forgot to create a PR. Thanks
