### ISSUE TITLE
proxy problem

### ISSUE THREAD

**Issue by sallsabil** [unreal4u/telegram-api#96]
Which version are you using?

> unreal4u/telegram-api         v3.4.1             A complete Telegram bot ...

Output:
[Tue Oct 16 15:27:32.431429 2018] [php7:error] [pid 2623] [client 31.204.150.103:22002] PHP Fatal error:  Allowed memory size of 524288000 bytes exhausted (tried to allocate 266342400 bytes) in /main.php on line 412
[Tue Oct 16 15:28:30.157748 2018] [php7:notice] [pid 2663] [client 31.204.150.103:13208] PHP Notice:  Undefined variable: WebhookInfo in /getupdates1.php on line 43
[Tue Oct 16 15:28:30.158014 2018] [php7:notice] [pid 2663] [client 31.204.150.103:13208] PHP Notice:  Trying to get property 'pending_update_count' of non-object in /getupdates1.php on line 43

I receive updates but my server can't communicate with Telegram's server.

What is the problem ?

**Comment by sallsabil** [comment]
Solved
I didn't change the webhook of settings to new one.

**Comment by unreal4u** [comment]
The speed will depend on your proxy, if your proxy is fast, the speed will be fast... Sorry I can't do anything about that :(

Greetings.
