### ISSUE TITLE
The `LeaveChat` comment is strange.

### ISSUE THREAD

**Issue by ujuc** [unreal4u/telegram-api#99]
## Which version are you using?

Hint: find out with composer which version you are currently running:  
`composer.phar show | grep telegram-api`

Output:
```
unreal4u/telegram-api              v3.4.1   A complete Telegram bot API implementation written in PHP, with support for inline bots!
```

## Description of problem

My chatbot leave my group.
I using `LeaveChat`, see comment.

https://github.com/unreal4u/telegram-api/blob/master/src/Telegram/Methods/LeaveChat.php#L18

This comment is `KickChatMember` url.
Is this `LeaveChat` method right??

Thanks.

**Comment by unreal4u** [comment]
Hi! 

Thanks for noticing this copy-paste error. I fixed it in master, so it will be present in the next version.

This is only a comment and does nothing with the code itself, so the method should be working fine.

**Comment by ujuc** [comment]
Oh~

Thanks 👍.
